version: '3.8'

services:
  backend:
    build: ./backend
    container_name: devscope_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - devscope_data:/app/data  # This saves your DB permanently
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: devscope_frontend
    restart: always
    ports:
      - "80:80"  # Production uses standard Port 80
    depends_on:
      - backend

volumes:
  devscope_data: # Define the permanent storage volume